"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorCode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _ErrorCode.ValueType  # 0
    FIT_NOT_IMPLEMENTED: _ErrorCode.ValueType  # 1
    EVALUATE_NOT_IMPLEMENTED: _ErrorCode.ValueType  # 2
    ROAMING_FAILED: _ErrorCode.ValueType  # 3
class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper):
    pass

OK: ErrorCode.ValueType  # 0
FIT_NOT_IMPLEMENTED: ErrorCode.ValueType  # 1
EVALUATE_NOT_IMPLEMENTED: ErrorCode.ValueType  # 2
ROAMING_FAILED: ErrorCode.ValueType  # 3
global___ErrorCode = ErrorCode


class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ERROR_CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    error_code: global___ErrorCode.ValueType
    message: typing.Text
    def __init__(self,
        *,
        error_code: global___ErrorCode.ValueType = ...,
        message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_code",b"error_code","message",b"message"]) -> None: ...
global___Status = Status

class Parameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TENSORS_FIELD_NUMBER: builtins.int
    TENSOR_TYPE_FIELD_NUMBER: builtins.int
    @property
    def tensors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    tensor_type: typing.Text
    def __init__(self,
        *,
        tensors: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        tensor_type: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tensor_type",b"tensor_type","tensors",b"tensors"]) -> None: ...
global___Parameters = Parameters

class InnerList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INNER_LIST_FIELD_NUMBER: builtins.int
    @property
    def inner_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Element]: ...
    def __init__(self,
        *,
        inner_list: typing.Optional[typing.Iterable[global___Element]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["inner_list",b"inner_list"]) -> None: ...
global___InnerList = InnerList

class InnerMap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class InnerMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___Element: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___Element] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    INNER_MAP_FIELD_NUMBER: builtins.int
    @property
    def inner_map(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___Element]: ...
    def __init__(self,
        *,
        inner_map: typing.Optional[typing.Mapping[typing.Text, global___Element]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["inner_map",b"inner_map"]) -> None: ...
global___InnerMap = InnerMap

class InnerMapInt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class InnerMapIntEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___Element: ...
        def __init__(self,
            *,
            key: builtins.int = ...,
            value: typing.Optional[global___Element] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    INNER_MAP_INT_FIELD_NUMBER: builtins.int
    @property
    def inner_map_int(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___Element]: ...
    def __init__(self,
        *,
        inner_map_int: typing.Optional[typing.Mapping[builtins.int, global___Element]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["inner_map_int",b"inner_map_int"]) -> None: ...
global___InnerMapInt = InnerMapInt

class Element(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOUBLE_FIELD_NUMBER: builtins.int
    SINT64_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    INNER_MAP_FIELD_NUMBER: builtins.int
    INNER_MAP_INT_FIELD_NUMBER: builtins.int
    INNER_LIST_FIELD_NUMBER: builtins.int
    double: builtins.float
    sint64: builtins.int
    """float float = 2;
    int32 int32 = 3;
    int64 int64 = 4;
    uint32 uint32 = 5;
    uint64 uint64 = 6;
    sint32 sint32 = 7;
    """

    bool: builtins.bool
    """fixed32 fixed32 = 9;
    fixed64 fixed64 = 10;
    sfixed32 sfixed32 = 11;
    sfixed64 sfixed64 = 12;
    """

    string: typing.Text
    bytes: builtins.bytes
    @property
    def inner_map(self) -> global___InnerMap: ...
    @property
    def inner_map_int(self) -> global___InnerMapInt: ...
    @property
    def inner_list(self) -> global___InnerList: ...
    def __init__(self,
        *,
        double: builtins.float = ...,
        sint64: builtins.int = ...,
        bool: builtins.bool = ...,
        string: typing.Text = ...,
        bytes: builtins.bytes = ...,
        inner_map: typing.Optional[global___InnerMap] = ...,
        inner_map_int: typing.Optional[global___InnerMapInt] = ...,
        inner_list: typing.Optional[global___InnerList] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool",b"bool","bytes",b"bytes","double",b"double","element",b"element","inner_list",b"inner_list","inner_map",b"inner_map","inner_map_int",b"inner_map_int","sint64",b"sint64","string",b"string"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool",b"bool","bytes",b"bytes","double",b"double","element",b"element","inner_list",b"inner_list","inner_map",b"inner_map","inner_map_int",b"inner_map_int","sint64",b"sint64","string",b"string"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["element",b"element"]) -> typing.Optional[typing_extensions.Literal["double","sint64","bool","string","bytes","inner_map","inner_map_int","inner_list"]]: ...
global___Element = Element

class ServerMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class FitIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> global___InnerMap: ...
        def __init__(self,
            *,
            parameters: typing.Optional[global___Parameters] = ...,
            config: typing.Optional[global___InnerMap] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["config",b"config","parameters",b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config",b"config","parameters",b"parameters"]) -> None: ...

    class EvaluateIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> global___InnerMap: ...
        def __init__(self,
            *,
            parameters: typing.Optional[global___Parameters] = ...,
            config: typing.Optional[global___InnerMap] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["config",b"config","parameters",b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config",b"config","parameters",b"parameters"]) -> None: ...

    class ServerReceivedSignal(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    class ServerStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        status: typing.Text
        def __init__(self,
            *,
            status: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    FIT_INS_FIELD_NUMBER: builtins.int
    EVALUATE_INS_FIELD_NUMBER: builtins.int
    SERVER_RECEIVED_SIGNAL_FIELD_NUMBER: builtins.int
    SERVER_STATUS_FIELD_NUMBER: builtins.int
    @property
    def fit_ins(self) -> global___ServerMessage.FitIns: ...
    @property
    def evaluate_ins(self) -> global___ServerMessage.EvaluateIns: ...
    @property
    def server_received_signal(self) -> global___ServerMessage.ServerReceivedSignal: ...
    @property
    def server_status(self) -> global___ServerMessage.ServerStatus: ...
    def __init__(self,
        *,
        fit_ins: typing.Optional[global___ServerMessage.FitIns] = ...,
        evaluate_ins: typing.Optional[global___ServerMessage.EvaluateIns] = ...,
        server_received_signal: typing.Optional[global___ServerMessage.ServerReceivedSignal] = ...,
        server_status: typing.Optional[global___ServerMessage.ServerStatus] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["evaluate_ins",b"evaluate_ins","fit_ins",b"fit_ins","msg",b"msg","server_received_signal",b"server_received_signal","server_status",b"server_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["evaluate_ins",b"evaluate_ins","fit_ins",b"fit_ins","msg",b"msg","server_received_signal",b"server_received_signal","server_status",b"server_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg",b"msg"]) -> typing.Optional[typing_extensions.Literal["fit_ins","evaluate_ins","server_received_signal","server_status"]]: ...
global___ServerMessage = ServerMessage

class ClientMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class FitRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> global___InnerMap: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            parameters: typing.Optional[global___Parameters] = ...,
            config: typing.Optional[global___InnerMap] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["config",b"config","parameters",b"parameters","status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config",b"config","parameters",b"parameters","status",b"status"]) -> None: ...

    class EvaluateRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def config(self) -> global___InnerMap: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            config: typing.Optional[global___InnerMap] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["config",b"config","status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config",b"config","status",b"status"]) -> None: ...

    class ClientStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        status: typing.Text
        def __init__(self,
            *,
            status: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    class ClientUploadingSignal(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    class ClientRoamingSignal(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    class RoamingTerminationSignal(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    class Shutdown(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STATUS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        def __init__(self,
            *,
            status: typing.Optional[global___Status] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...

    FIT_RES_FIELD_NUMBER: builtins.int
    EVALUATE_RES_FIELD_NUMBER: builtins.int
    CLIENT_STATUS_FIELD_NUMBER: builtins.int
    CLIENT_UPLOADING_SIGNAL_FIELD_NUMBER: builtins.int
    CLIENT_ROAMING_SIGNAL_FIELD_NUMBER: builtins.int
    ROAMING_TERMINATION_SIGNAL_FIELD_NUMBER: builtins.int
    SHUTDOWN_FIELD_NUMBER: builtins.int
    @property
    def fit_res(self) -> global___ClientMessage.FitRes: ...
    @property
    def evaluate_res(self) -> global___ClientMessage.EvaluateRes: ...
    @property
    def client_status(self) -> global___ClientMessage.ClientStatus: ...
    @property
    def client_uploading_signal(self) -> global___ClientMessage.ClientUploadingSignal: ...
    @property
    def client_roaming_signal(self) -> global___ClientMessage.ClientRoamingSignal: ...
    @property
    def roaming_termination_signal(self) -> global___ClientMessage.RoamingTerminationSignal: ...
    @property
    def shutdown(self) -> global___ClientMessage.Shutdown: ...
    def __init__(self,
        *,
        fit_res: typing.Optional[global___ClientMessage.FitRes] = ...,
        evaluate_res: typing.Optional[global___ClientMessage.EvaluateRes] = ...,
        client_status: typing.Optional[global___ClientMessage.ClientStatus] = ...,
        client_uploading_signal: typing.Optional[global___ClientMessage.ClientUploadingSignal] = ...,
        client_roaming_signal: typing.Optional[global___ClientMessage.ClientRoamingSignal] = ...,
        roaming_termination_signal: typing.Optional[global___ClientMessage.RoamingTerminationSignal] = ...,
        shutdown: typing.Optional[global___ClientMessage.Shutdown] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["client_roaming_signal",b"client_roaming_signal","client_status",b"client_status","client_uploading_signal",b"client_uploading_signal","evaluate_res",b"evaluate_res","fit_res",b"fit_res","msg",b"msg","roaming_termination_signal",b"roaming_termination_signal","shutdown",b"shutdown"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_roaming_signal",b"client_roaming_signal","client_status",b"client_status","client_uploading_signal",b"client_uploading_signal","evaluate_res",b"evaluate_res","fit_res",b"fit_res","msg",b"msg","roaming_termination_signal",b"roaming_termination_signal","shutdown",b"shutdown"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg",b"msg"]) -> typing.Optional[typing_extensions.Literal["fit_res","evaluate_res","client_status","client_uploading_signal","client_roaming_signal","roaming_termination_signal","shutdown"]]: ...
global___ClientMessage = ClientMessage
